export const COLOMBIA_LOCATIONS: Record<string, string[]> = {
  "Amazonas": ["Leticia", "Puerto Nariño", "El Encanto", "La Chorrera", "Puerto Alegría", "Puerto Arica", "Tarapacá"],
  "Antioquia": ["Medellín", "Bello", "Itagüí", "Envigado", "Apartadó", "Turbo", "Rionegro", "Caucasia", "Manizales (Antioquia)", "Sabaneta", "La Estrella", "Caldas", "Copacabana", "Girardota", "Barbosa", "Andes", "Santa Fe de Antioquia", "Yarumal", "Puerto Berrío", "Marinilla", "El Carmen de Viboral", "Guarne", "La Ceja", "Montería (Antioquia)", "Amagá", "Cisneros", "Segovia", "Remedios", "El Bagre", "Zaragoza"],
  "Arauca": ["Arauca", "Arauquita", "Fortul", "Puerto Rondón", "Saravena", "Tame", "Cravo Norte"],
  "Atlántico": ["Barranquilla", "Soledad", "Malambo", "Sabanalarga", "Baranoa", "Galapa", "Puerto Colombia", "Polonuevo", "Ponedera", "Tubará", "Luruaco", "Repelón", "Usiacurí", "Palmar de Varela"],
  "Bogotá D.C.": ["Bogotá"],
  "Bolívar": ["Cartagena", "Magangué", "El Carmen de Bolívar", "Mompós", "Turbaco", "Arjona", "San Juan Nepomuceno", "San Pablo", "Simití", "Zambrano", "Córdoba (Bolívar)", "Margarita", "San Martín de Loba"],
  "Boyacá": ["Tunja", "Duitama", "Sogamoso", "Chiquinquirá", "Paipa", "Moniquirá", "Puerto Boyacá", "Garagoa", "Soatá", "Villa de Leyva", "Miraflores", "Guateque", "Samacá", "Tuta", "Nobsa"],
  "Caldas": ["Manizales", "La Dorada", "Riosucio", "Chinchiná", "Villamaría", "Palestina", "Anserma", "Salamina", "Supía", "Manzanares", "Pensilvania", "Aguadas", "Neira", "Viterbo"],
  "Caquetá": ["Florencia", "San Vicente del Caguán", "Puerto Rico", "La Montañita", "El Doncello", "El Paujil", "Belén de los Andaquíes", "Albania", "Cartagena del Chairá", "Solano", "Valparaíso"],
  "Casanare": ["Yopal", "Aguazul", "Villanueva", "Tauramena", "Monterrey", "Paz de Ariporo", "Nunchía", "Orocué", "Trinidad", "Pore", "San Luis de Palenque", "Hato Corozal"],
  "Cauca": ["Popayán", "Santander de Quilichao", "Puerto Tejada", "Patía", "Miranda", "Corinto", "Caloto", "Piendamó", "Silvia", "Totoró", "Coconuco", "La Vega", "El Tambo", "Mercaderes"],
  "Cesar": ["Valledupar", "Aguachica", "Agustín Codazzi", "La Paz", "Bosconia", "Curumaní", "Pelaya", "Chimichagua", "Tamalameque", "San Diego", "Astrea", "La Gloria", "Pueblo Bello"],
  "Chocó": ["Quibdó", "Istmina", "Tadó", "Riosucio (Chocó)", "Bojayá", "Condoto", "El Carmen de Atrato", "Bagadó", "Acandí", "Bahía Solano", "Juradó", "Nuquí"],
  "Córdoba": ["Montería", "Lorica", "Cereté", "Sahagún", "Montelíbano", "Puerto Libertador", "Tierralta", "Valencia", "Chinú", "San Pelayo", "Ciénaga de Oro", "Ayapel", "La Apartada"],
  "Cundinamarca": ["Soacha", "Zipaquirá", "Facatativá", "Chía", "Fusagasugá", "Girardot", "Mosquera", "Madrid", "Funza", "Cajicá", "Tocancipá", "La Calera", "Cota", "Sopó", "Tenjo", "Tabio", "Subachoque", "El Rosal", "Bojacá", "Ubaté", "Simijaca", "Guatavita", "Chocontá", "Gachetá", "Villeta", "Nocaima", "La Mesa", "Anapoima", "Viotá", "Arbeláez", "San Bernardo", "Silvania"],
  "Guainía": ["Inírida", "Barranco Minas", "Mapiripana", "San Felipe", "Puerto Colombia (Guainía)", "La Guadalupe", "Cacahual"],
  "Guaviare": ["San José del Guaviare", "El Retorno", "Calamar", "Miraflores (Guaviare)"],
  "Huila": ["Neiva", "Pitalito", "Garzón", "La Plata", "Campoalegre", "Rivera", "Palermo", "Timaná", "San Agustín", "Isnos", "Algeciras", "Gigante", "Baraya", "Íquira"],
  "La Guajira": ["Riohacha", "Maicao", "Uribia", "Manaure", "Fonseca", "San Juan del Cesar", "Barrancas", "Albania", "Distracción", "El Molino", "Villanueva (La Guajira)", "Hatonuevo"],
  "Magdalena": ["Santa Marta", "Ciénaga", "Fundación", "El Banco", "Plato", "Aracataca", "Pivijay", "Salamina (Magdalena)", "San Zenón", "Santa Bárbara de Pinto", "Tenerife", "Zona Bananera"],
  "Meta": ["Villavicencio", "Acacías", "Granada", "San Martín", "Puerto López", "La Macarena", "Cumaral", "Restrepo", "Fuente de Oro", "Puerto Gaitán", "Castilla la Nueva", "El Dorado", "Guamal", "Lejanías"],
  "Nariño": ["Pasto", "Tumaco", "Ipiales", "Túquerres", "La Unión (Nariño)", "Samaniego", "Barbacoas", "Sandoná", "El Charco", "Olaya Herrera", "Cumbal", "Pupiales", "Consacá", "Linares"],
  "Norte de Santander": ["Cúcuta", "Ocaña", "Pamplona", "Villa del Rosario", "Los Patios", "El Zulia", "Tibú", "Sardinata", "Chinácota", "Bucarasica", "Ábrego", "La Playa de Belén", "Convención"],
  "Putumayo": ["Mocoa", "Puerto Asís", "Orito", "Valle del Guamuez", "Villagarzón", "San Miguel (Putumayo)", "Puerto Caicedo", "Puerto Guzmán", "Puerto Leguízamo", "Sibundoy", "Colón (Putumayo)", "Santiago (Putumayo)"],
  "Quindío": ["Armenia", "Calarcá", "Montenegro", "Quimbaya", "La Tebaida", "Circasia", "Filandia", "Salento", "Génova", "Pijao", "Córdoba (Quindío)", "Buenavista (Quindío)"],
  "Risaralda": ["Pereira", "Dosquebradas", "Santa Rosa de Cabal", "La Virginia", "Cartago (Risaralda)", "Belén de Umbría", "Marsella", "Guática", "Quinchía", "Mistrató", "Pueblo Rico", "Balboa (Risaralda)", "Apía", "Santuario (Risaralda)"],
  "San Andrés y Providencia": ["San Andrés", "Providencia", "Santa Catalina"],
  "Santander": ["Bucaramanga", "Floridablanca", "Girón", "Piedecuesta", "Barrancabermeja", "San Gil", "Socorro", "Vélez", "Málaga", "Barbosa (Santander)", "Lebrija", "Rionegro (Santander)", "Puerto Wilches", "Sabana de Torres", "Charalá", "Oiba", "Suaita"],
  "Sucre": ["Sincelejo", "Corozal", "Sampués", "San Marcos", "Majagual", "Tolú", "Morroa", "Ovejas", "San Onofre", "Guaranda", "Coveñas", "El Roble", "Los Palmitos"],
  "Tolima": ["Ibagué", "Espinal", "Honda", "Melgar", "Chaparral", "El Guamo", "Mariquita", "Líbano", "Purificación", "Flandes", "Rioblanco", "Villahermosa", "Ambalema", "Planadas", "Rovira"],
  "Valle del Cauca": ["Cali", "Buenaventura", "Palmira", "Tuluá", "Buga", "Cartago", "Yumbo", "Jamundí", "Candelaria", "Florida", "Pradera", "Zarzal", "La Unión (Valle)", "Roldanillo", "Sevilla (Valle)", "El Cerrito", "Ginebra", "Dagua", "Restrepo (Valle)", "La Cumbre", "Vijes", "Yotoco", "Bugalagrande"],
  "Vaupés": ["Mitú", "Carurú", "Papunaua", "Taraira", "Pacoa", "Yavaraté"],
  "Vichada": ["Puerto Carreño", "La Primavera", "Santa Rosalía", "Cumaribo"],
}

export const COLOMBIA_DEPARTMENTS = Object.keys(COLOMBIA_LOCATIONS).sort()
